# Generated by Django 3.2.7 on 2021-09-03 11:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='닉네임',
            new_name='이름',
        ),
        migrations.RemoveField(
            model_name='user',
            name='나이',
        ),
        migrations.RemoveField(
            model_name='user',
            name='연애횟수',
        ),
        migrations.RemoveField(
            model_name='user',
            name='직업',
        ),
        migrations.AddField(
            model_name='user',
            name='생년월일',
            field=models.DateField(null=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='성별',
            field=models.SmallIntegerField(choices=[(0, '남성'), (1, '여성')]),
        ),
    ]
