# Generated by Django 3.2.2 on 2021-11-16 08:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('openapp', '0001_initial'),
        ('scheduleapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='schedule_1',
            name='post',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='schedule_1', to='openapp.open_1'),
        ),
    ]
