# Generated by Django 3.2.6 on 2021-11-17 07:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('scheduleapp', '0003_schedule_1_writer'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='schedule_1',
            name='post',
        ),
    ]
