# Generated by Django 3.2.6 on 2021-09-03 13:03

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('openapp_1', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='open_1',
            name='number',
            field=models.IntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(50)]),
        ),
    ]
