# Generated by Django 3.2.2 on 2021-11-02 15:01

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('openapp', '0002_auto_20211102_1830'),
    ]

    operations = [
        migrations.AddField(
            model_name='open_1',
            name='like_users',
            field=models.ManyToManyField(blank=True, related_name='like_posts', to=settings.AUTH_USER_MODEL),
        ),
    ]
