# Generated by Django 3.2.7 on 2021-09-30 06:43

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('openapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Write_1',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('제목', models.CharField(max_length=200)),
                ('내용', models.TextField()),
                ('사진', models.ImageField(blank=True, null=True, upload_to='Write_1')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('post', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='writes', to='openapp.open_1')),
            ],
        ),
    ]
